# etcdOperator
etcdOperator:
  image:
    repository: quay.io/coreos/etcd-operator
    tag: v0.9.4
# backup spec
backupOperator:
  image:
    repository: quay.io/coreos/etcd-operator
    tag: v0.9.4
  spec:
    storageType: S3
    s3:
      s3Bucket:
      awsSecret:
# restore spec
restoreOperator:
  image:
    repository: quay.io/coreos/etcd-operator
    tag: v0.9.4
  spec:
    s3:
      # The format of "path" must be: "<s3-bucket-name>/<path-to-backup-file>"
      # e.g: "etcd-snapshot-bucket/v1/default/example-etcd-cluster/3.2.10_0000000000000001_etcd.backup"
      path:
      awsSecret:
## etcd-cluster specific values
etcdCluster:
  name: etcd-cluster
  size: 3
  version: 3.4.0
  image:
    repository: quay.io/coreos/etcd
    tag: v3.4.0
  enableTLS: false
  # TLS configs
  tls:
    static:
      member:
        peerSecret: etcd-peer-tls
        serverSecret: etcd-server-tls
      operatorSecret: etcd-client-tls